name: Build
permissions:
  contents: read

on:
  push:
    branches:
      - "kurth4cker"
      - "ci-*"
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 18 * * 0"



jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CFLAGS: -Wall -Wextra -Werror

    steps:
      - name: Install dependencies
        run: sudo apt update && sudo apt install -y fpc

      - name: Checkout
        uses: actions/checkout@v6

      - name: Build mine
        run: make mine

      - name: Build agent
        run: make agent
